# syntax=docker/dockerfile:1

FROM alpine:latest as bootstrap-stage
ADD scripts /src/scripts
RUN sh /src/scripts/build-bootstrap.sh

FROM bootstrap-stage as build-stage
ADD patches /src/patches
WORKDIR /src
ARG VERSION
RUN sh /src/scripts/build.sh "$VERSION"

FROM scratch AS export-stage
COPY --from=build-stage /src/openvpn /
