# syntax=docker/dockerfile:1

FROM alpine:latest AS bootstrap-stage
ADD scripts /src/scripts
RUN sh /src/scripts/addpatch-bootstrap.sh

FROM bootstrap-stage AS patch-stage
ADD patches /src/patches
WORKDIR /src
ARG VERSION_A
ARG VERSION_B
RUN sh /src/scripts/addpatch.sh "$VERSION_A" "$VERSION_B"

FROM scratch AS export-stage
ARG VERSION_B
COPY --from=patch-stage "/src/patches/openvpn-$VERSION_B.patch" /
