# syntax=docker/dockerfile:1

FROM alpine:latest AS bootstrap-stage
ADD openvpn/scripts /src/scripts
RUN sh /src/scripts/build-bootstrap.sh

FROM bootstrap-stage AS build-stage
ADD openvpn/patches /src/patches
WORKDIR /src
ARG VERSION
RUN sh /src/scripts/build.sh "$VERSION"

FROM scratch AS export-stage
COPY --from=build-stage /src/openvpn /
